/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;

/**
 *
 * @author calde
 */
public class RightSidebar extends javax.swing.JPanel {

    /**
     * Creates new form sidebar
     */
    public RightSidebar() {
        initComponents();
          
        jScrollBar1.addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
               
                jScrollBar1.setValue(jScrollBar1.getValue() + e.getUnitsToScroll());
             
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();

        setLayout(new java.awt.GridLayout(1, 0));

        jScrollBar1.setBlockIncrement(5);
        jScrollBar1.setMaximum(30);
        jScrollBar1.setMinimum(1);
        jScrollBar1.setToolTipText("");
        jScrollBar1.setPreferredSize(new java.awt.Dimension(7, 800));
        add(jScrollBar1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
